run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - sqlclosecheck
    - gocritic
    - revive

linters-settings:
  errcheck:
    # Exclude common patterns where errors are intentionally ignored
    exclude-functions:
      - encoding/json.(*Encoder).Encode
      - encoding/json.Unmarshal
      - (*github.com/spf13/cobra.Command).Help
      - (*github.com/spf13/cobra.Command).MarkFlagRequired
      - (*database/sql.Tx).Rollback
      - crypto/rand.Read
      - io.Writer.Write
      - (*os.File).Seek
      - (*golang.org/x/crypto/ssh.Session).Signal
      - (*encoding/csv.Writer).Write

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (allow for deferred closes)
      - G115 # Integer overflow conversion (safe for bounded values like buffer sizes)
      - G304 # File path provided as taint input (allow for config files)
      - G402 # TLS MinVersion (configurable, not a hardcoded vulnerability)
      - G404 # Weak random generator (acceptable for non-crypto uses like jitter)

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

  misspell:
    locale: US

issues:
  exclude-rules:
    # Test files can have longer functions and more complexity
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - errcheck

    # Generated proto files
    - path: \.pb\.go$
      linters:
        - all

    # Generated templ files
    - path: _templ\.go$
      linters:
        - all

  max-issues-per-linter: 50
  max-same-issues: 10
