version: "2"
run:
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - gosec
    - misspell
    - noctx
    - unconvert
  disable:
    - errcheck
  settings:
    gosec:
      excludes:
        - G104
        - G106
        - G115
        - G201
        - G304
        - G402
        - G404
      severity: medium
      confidence: medium
    govet:
      disable:
        - shadow
        - fieldalignment
        - unusedwrite
      enable-all: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - all
        path: \.pb\.go$
      - linters:
          - all
        path: _templ\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
