run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - sqlclosecheck
    - gocritic
    - revive

linters-settings:
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (allow for deferred closes)
      - G304 # File path provided as taint input (allow for config files)

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

  misspell:
    locale: US

issues:
  exclude-rules:
    # Test files can have longer functions and more complexity
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - errcheck

    # Generated proto files
    - path: \.pb\.go$
      linters:
        - all

    # Generated templ files
    - path: _templ\.go$
      linters:
        - all

  max-issues-per-linter: 50
  max-same-issues: 10
