// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blazelog/v1/agent.proto

package blazelogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandType defines types of server-to-agent commands.
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED   CommandType = 0
	CommandType_COMMAND_TYPE_RELOAD_CONFIG CommandType = 1
	CommandType_COMMAND_TYPE_PAUSE         CommandType = 2
	CommandType_COMMAND_TYPE_RESUME        CommandType = 3
	CommandType_COMMAND_TYPE_SHUTDOWN      CommandType = 4
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_RELOAD_CONFIG",
		2: "COMMAND_TYPE_PAUSE",
		3: "COMMAND_TYPE_RESUME",
		4: "COMMAND_TYPE_SHUTDOWN",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":   0,
		"COMMAND_TYPE_RELOAD_CONFIG": 1,
		"COMMAND_TYPE_PAUSE":         2,
		"COMMAND_TYPE_RESUME":        3,
		"COMMAND_TYPE_SHUTDOWN":      4,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_blazelog_v1_agent_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_blazelog_v1_agent_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_blazelog_v1_agent_proto_rawDescGZIP(), []int{0}
}

// AgentInfo contains information about a BlazeLog agent.
type AgentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the agent.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Human-readable name for the agent.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Hostname where agent is running.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Agent version string.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Operating system (linux, darwin, windows).
	Os string `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	// CPU architecture (amd64, arm64).
	Arch string `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	// Labels for grouping/filtering agents.
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// List of log sources configured on this agent.
	Sources []*LogSource `protobuf:"bytes,8,rep,name=sources,proto3" json:"sources,omitempty"`
	// Project this agent belongs to.
	ProjectId     string `protobuf:"bytes,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_blazelog_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentInfo) GetSources() []*LogSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *AgentInfo) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// LogSource describes a log file being monitored.
type LogSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of this source.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Path pattern (may include globs).
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Log type for parsing.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Whether tailing is enabled.
	Follow        bool `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSource) Reset() {
	*x = LogSource{}
	mi := &file_blazelog_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSource) ProtoMessage() {}

func (x *LogSource) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSource.ProtoReflect.Descriptor instead.
func (*LogSource) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *LogSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogSource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogSource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogSource) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

// RegisterRequest is sent when an agent connects.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_blazelog_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

// RegisterResponse confirms registration.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether registration was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if registration failed.
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Server-assigned agent ID (may differ from requested).
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Stream configuration from server.
	Config        *StreamConfig `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_blazelog_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *StreamConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// StreamConfig contains server-side stream configuration.
type StreamConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum batch size for log entries.
	MaxBatchSize int32 `protobuf:"varint,1,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`
	// Maximum time to buffer before sending (milliseconds).
	FlushIntervalMs int32 `protobuf:"varint,2,opt,name=flush_interval_ms,json=flushIntervalMs,proto3" json:"flush_interval_ms,omitempty"`
	// Whether compression is enabled.
	CompressionEnabled bool `protobuf:"varint,3,opt,name=compression_enabled,json=compressionEnabled,proto3" json:"compression_enabled,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamConfig) Reset() {
	*x = StreamConfig{}
	mi := &file_blazelog_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfig) ProtoMessage() {}

func (x *StreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfig.ProtoReflect.Descriptor instead.
func (*StreamConfig) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *StreamConfig) GetMaxBatchSize() int32 {
	if x != nil {
		return x.MaxBatchSize
	}
	return 0
}

func (x *StreamConfig) GetFlushIntervalMs() int32 {
	if x != nil {
		return x.FlushIntervalMs
	}
	return 0
}

func (x *StreamConfig) GetCompressionEnabled() bool {
	if x != nil {
		return x.CompressionEnabled
	}
	return false
}

// HeartbeatRequest is sent periodically by agents.
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent sending the heartbeat.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// When this heartbeat was generated.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Agent status metrics.
	Status        *AgentStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_blazelog_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AgentStatus contains runtime status of an agent.
type AgentStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of log entries processed since last heartbeat.
	EntriesProcessed uint64 `protobuf:"varint,1,opt,name=entries_processed,json=entriesProcessed,proto3" json:"entries_processed,omitempty"`
	// Number of entries currently buffered.
	BufferSize uint64 `protobuf:"varint,2,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	// Number of active file watchers.
	ActiveSources int32 `protobuf:"varint,3,opt,name=active_sources,json=activeSources,proto3" json:"active_sources,omitempty"`
	// Any errors encountered.
	Errors []string `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	// Memory usage in bytes.
	MemoryBytes uint64 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// CPU usage percentage (0-100).
	CpuPercent    float32 `protobuf:"fixed32,6,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_blazelog_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentStatus) GetEntriesProcessed() uint64 {
	if x != nil {
		return x.EntriesProcessed
	}
	return 0
}

func (x *AgentStatus) GetBufferSize() uint64 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *AgentStatus) GetActiveSources() int32 {
	if x != nil {
		return x.ActiveSources
	}
	return 0
}

func (x *AgentStatus) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *AgentStatus) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *AgentStatus) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

// HeartbeatResponse acknowledges heartbeat and may include commands.
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether heartbeat was acknowledged.
	Acknowledged bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// Optional command for agent to execute.
	Command       *ServerCommand `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_blazelog_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetCommand() *ServerCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

// ServerCommand represents a command from server to agent.
type ServerCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of command.
	Type CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=blazelog.v1.CommandType" json:"type,omitempty"`
	// Command-specific payload.
	Parameters    map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_blazelog_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ServerCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *ServerCommand) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

var File_blazelog_v1_agent_proto protoreflect.FileDescriptor

const file_blazelog_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x17blazelog/v1/agent.proto\x12\vblazelog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x02\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12:\n" +
	"\x06labels\x18\a \x03(\v2\".blazelog.v1.AgentInfo.LabelsEntryR\x06labels\x120\n" +
	"\asources\x18\b \x03(\v2\x16.blazelog.v1.LogSourceR\asources\x12\x1d\n" +
	"\n" +
	"project_id\x18\t \x01(\tR\tprojectId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\tLogSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\"?\n" +
	"\x0fRegisterRequest\x12,\n" +
	"\x05agent\x18\x01 \x01(\v2\x16.blazelog.v1.AgentInfoR\x05agent\"\x9f\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x121\n" +
	"\x06config\x18\x04 \x01(\v2\x19.blazelog.v1.StreamConfigR\x06config\"\x91\x01\n" +
	"\fStreamConfig\x12$\n" +
	"\x0emax_batch_size\x18\x01 \x01(\x05R\fmaxBatchSize\x12*\n" +
	"\x11flush_interval_ms\x18\x02 \x01(\x05R\x0fflushIntervalMs\x12/\n" +
	"\x13compression_enabled\x18\x03 \x01(\bR\x12compressionEnabled\"\x99\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x120\n" +
	"\x06status\x18\x03 \x01(\v2\x18.blazelog.v1.AgentStatusR\x06status\"\xde\x01\n" +
	"\vAgentStatus\x12+\n" +
	"\x11entries_processed\x18\x01 \x01(\x04R\x10entriesProcessed\x12\x1f\n" +
	"\vbuffer_size\x18\x02 \x01(\x04R\n" +
	"bufferSize\x12%\n" +
	"\x0eactive_sources\x18\x03 \x01(\x05R\ractiveSources\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\x12\x1f\n" +
	"\vcpu_percent\x18\x06 \x01(\x02R\n" +
	"cpuPercent\"m\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x124\n" +
	"\acommand\x18\x02 \x01(\v2\x1a.blazelog.v1.ServerCommandR\acommand\"\xc8\x01\n" +
	"\rServerCommand\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.blazelog.v1.CommandTypeR\x04type\x12J\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2*.blazelog.v1.ServerCommand.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x97\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_RELOAD_CONFIG\x10\x01\x12\x16\n" +
	"\x12COMMAND_TYPE_PAUSE\x10\x02\x12\x17\n" +
	"\x13COMMAND_TYPE_RESUME\x10\x03\x12\x19\n" +
	"\x15COMMAND_TYPE_SHUTDOWN\x10\x04B\xb5\x01\n" +
	"\x0fcom.blazelog.v1B\n" +
	"AgentProtoP\x01ZIgithub.com/good-yellow-bee/blazelog/internal/proto/blazelog/v1;blazelogv1\xa2\x02\x03BXX\xaa\x02\vBlazelog.V1\xca\x02\vBlazelog\\V1\xe2\x02\x17Blazelog\\V1\\GPBMetadata\xea\x02\fBlazelog::V1b\x06proto3"

var (
	file_blazelog_v1_agent_proto_rawDescOnce sync.Once
	file_blazelog_v1_agent_proto_rawDescData []byte
)

func file_blazelog_v1_agent_proto_rawDescGZIP() []byte {
	file_blazelog_v1_agent_proto_rawDescOnce.Do(func() {
		file_blazelog_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blazelog_v1_agent_proto_rawDesc), len(file_blazelog_v1_agent_proto_rawDesc)))
	})
	return file_blazelog_v1_agent_proto_rawDescData
}

var file_blazelog_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blazelog_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_blazelog_v1_agent_proto_goTypes = []any{
	(CommandType)(0),              // 0: blazelog.v1.CommandType
	(*AgentInfo)(nil),             // 1: blazelog.v1.AgentInfo
	(*LogSource)(nil),             // 2: blazelog.v1.LogSource
	(*RegisterRequest)(nil),       // 3: blazelog.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 4: blazelog.v1.RegisterResponse
	(*StreamConfig)(nil),          // 5: blazelog.v1.StreamConfig
	(*HeartbeatRequest)(nil),      // 6: blazelog.v1.HeartbeatRequest
	(*AgentStatus)(nil),           // 7: blazelog.v1.AgentStatus
	(*HeartbeatResponse)(nil),     // 8: blazelog.v1.HeartbeatResponse
	(*ServerCommand)(nil),         // 9: blazelog.v1.ServerCommand
	nil,                           // 10: blazelog.v1.AgentInfo.LabelsEntry
	nil,                           // 11: blazelog.v1.ServerCommand.ParametersEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_blazelog_v1_agent_proto_depIdxs = []int32{
	10, // 0: blazelog.v1.AgentInfo.labels:type_name -> blazelog.v1.AgentInfo.LabelsEntry
	2,  // 1: blazelog.v1.AgentInfo.sources:type_name -> blazelog.v1.LogSource
	1,  // 2: blazelog.v1.RegisterRequest.agent:type_name -> blazelog.v1.AgentInfo
	5,  // 3: blazelog.v1.RegisterResponse.config:type_name -> blazelog.v1.StreamConfig
	12, // 4: blazelog.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 5: blazelog.v1.HeartbeatRequest.status:type_name -> blazelog.v1.AgentStatus
	9,  // 6: blazelog.v1.HeartbeatResponse.command:type_name -> blazelog.v1.ServerCommand
	0,  // 7: blazelog.v1.ServerCommand.type:type_name -> blazelog.v1.CommandType
	11, // 8: blazelog.v1.ServerCommand.parameters:type_name -> blazelog.v1.ServerCommand.ParametersEntry
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_blazelog_v1_agent_proto_init() }
func file_blazelog_v1_agent_proto_init() {
	if File_blazelog_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blazelog_v1_agent_proto_rawDesc), len(file_blazelog_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blazelog_v1_agent_proto_goTypes,
		DependencyIndexes: file_blazelog_v1_agent_proto_depIdxs,
		EnumInfos:         file_blazelog_v1_agent_proto_enumTypes,
		MessageInfos:      file_blazelog_v1_agent_proto_msgTypes,
	}.Build()
	File_blazelog_v1_agent_proto = out.File
	file_blazelog_v1_agent_proto_goTypes = nil
	file_blazelog_v1_agent_proto_depIdxs = nil
}
