// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blazelog/v1/alert.proto

package blazelogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Alert represents a triggered alert.
type Alert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the rule that triggered.
	RuleName string `protobuf:"bytes,1,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	// Rule description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Alert severity.
	Severity Severity `protobuf:"varint,3,opt,name=severity,proto3,enum=blazelog.v1.Severity" json:"severity,omitempty"`
	// Details about what triggered the alert.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// When the alert was triggered.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Number of matching events (for threshold alerts).
	Count int32 `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	// Configured threshold (for threshold alerts).
	Threshold int32 `protobuf:"varint,7,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// Configured window (for threshold alerts).
	Window string `protobuf:"bytes,8,opt,name=window,proto3" json:"window,omitempty"`
	// Log entry that triggered the alert (for pattern alerts).
	TriggeringEntry *LogEntry `protobuf:"bytes,9,opt,name=triggering_entry,json=triggeringEntry,proto3" json:"triggering_entry,omitempty"`
	// Notification channels.
	Notify []string `protobuf:"bytes,10,rep,name=notify,proto3" json:"notify,omitempty"`
	// Labels from the rule.
	Labels        map[string]string `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_blazelog_v1_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_alert_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *Alert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alert) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Alert) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Alert) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Alert) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *Alert) GetTriggeringEntry() *LogEntry {
	if x != nil {
		return x.TriggeringEntry
	}
	return nil
}

func (x *Alert) GetNotify() []string {
	if x != nil {
		return x.Notify
	}
	return nil
}

func (x *Alert) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_blazelog_v1_alert_proto protoreflect.FileDescriptor

const file_blazelog_v1_alert_proto_rawDesc = "" +
	"\n" +
	"\x17blazelog/v1/alert.proto\x12\vblazelog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18blazelog/v1/common.proto\x1a\x15blazelog/v1/log.proto\"\xe6\x03\n" +
	"\x05Alert\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x121\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x15.blazelog.v1.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\x12\x1c\n" +
	"\tthreshold\x18\a \x01(\x05R\tthreshold\x12\x16\n" +
	"\x06window\x18\b \x01(\tR\x06window\x12@\n" +
	"\x10triggering_entry\x18\t \x01(\v2\x15.blazelog.v1.LogEntryR\x0ftriggeringEntry\x12\x16\n" +
	"\x06notify\x18\n" +
	" \x03(\tR\x06notify\x126\n" +
	"\x06labels\x18\v \x03(\v2\x1e.blazelog.v1.Alert.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xb5\x01\n" +
	"\x0fcom.blazelog.v1B\n" +
	"AlertProtoP\x01ZIgithub.com/good-yellow-bee/blazelog/internal/proto/blazelog/v1;blazelogv1\xa2\x02\x03BXX\xaa\x02\vBlazelog.V1\xca\x02\vBlazelog\\V1\xe2\x02\x17Blazelog\\V1\\GPBMetadata\xea\x02\fBlazelog::V1b\x06proto3"

var (
	file_blazelog_v1_alert_proto_rawDescOnce sync.Once
	file_blazelog_v1_alert_proto_rawDescData []byte
)

func file_blazelog_v1_alert_proto_rawDescGZIP() []byte {
	file_blazelog_v1_alert_proto_rawDescOnce.Do(func() {
		file_blazelog_v1_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blazelog_v1_alert_proto_rawDesc), len(file_blazelog_v1_alert_proto_rawDesc)))
	})
	return file_blazelog_v1_alert_proto_rawDescData
}

var file_blazelog_v1_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blazelog_v1_alert_proto_goTypes = []any{
	(*Alert)(nil),                 // 0: blazelog.v1.Alert
	nil,                           // 1: blazelog.v1.Alert.LabelsEntry
	(Severity)(0),                 // 2: blazelog.v1.Severity
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*LogEntry)(nil),              // 4: blazelog.v1.LogEntry
}
var file_blazelog_v1_alert_proto_depIdxs = []int32{
	2, // 0: blazelog.v1.Alert.severity:type_name -> blazelog.v1.Severity
	3, // 1: blazelog.v1.Alert.timestamp:type_name -> google.protobuf.Timestamp
	4, // 2: blazelog.v1.Alert.triggering_entry:type_name -> blazelog.v1.LogEntry
	1, // 3: blazelog.v1.Alert.labels:type_name -> blazelog.v1.Alert.LabelsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_blazelog_v1_alert_proto_init() }
func file_blazelog_v1_alert_proto_init() {
	if File_blazelog_v1_alert_proto != nil {
		return
	}
	file_blazelog_v1_common_proto_init()
	file_blazelog_v1_log_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blazelog_v1_alert_proto_rawDesc), len(file_blazelog_v1_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blazelog_v1_alert_proto_goTypes,
		DependencyIndexes: file_blazelog_v1_alert_proto_depIdxs,
		MessageInfos:      file_blazelog_v1_alert_proto_msgTypes,
	}.Build()
	File_blazelog_v1_alert_proto = out.File
	file_blazelog_v1_alert_proto_goTypes = nil
	file_blazelog_v1_alert_proto_depIdxs = nil
}
