// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blazelog/v1/common.proto

package blazelogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogLevel represents the severity level of a log entry.
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARNING     LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
	LogLevel_LOG_LEVEL_FATAL       LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARNING",
		4: "LOG_LEVEL_ERROR",
		5: "LOG_LEVEL_FATAL",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARNING":     3,
		"LOG_LEVEL_ERROR":       4,
		"LOG_LEVEL_FATAL":       5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_blazelog_v1_common_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_blazelog_v1_common_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_blazelog_v1_common_proto_rawDescGZIP(), []int{0}
}

// LogType represents the type/source of the log.
type LogType int32

const (
	LogType_LOG_TYPE_UNSPECIFIED LogType = 0
	LogType_LOG_TYPE_NGINX       LogType = 1
	LogType_LOG_TYPE_APACHE      LogType = 2
	LogType_LOG_TYPE_MAGENTO     LogType = 3
	LogType_LOG_TYPE_PRESTASHOP  LogType = 4
	LogType_LOG_TYPE_WORDPRESS   LogType = 5
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "LOG_TYPE_UNSPECIFIED",
		1: "LOG_TYPE_NGINX",
		2: "LOG_TYPE_APACHE",
		3: "LOG_TYPE_MAGENTO",
		4: "LOG_TYPE_PRESTASHOP",
		5: "LOG_TYPE_WORDPRESS",
	}
	LogType_value = map[string]int32{
		"LOG_TYPE_UNSPECIFIED": 0,
		"LOG_TYPE_NGINX":       1,
		"LOG_TYPE_APACHE":      2,
		"LOG_TYPE_MAGENTO":     3,
		"LOG_TYPE_PRESTASHOP":  4,
		"LOG_TYPE_WORDPRESS":   5,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_blazelog_v1_common_proto_enumTypes[1].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_blazelog_v1_common_proto_enumTypes[1]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_blazelog_v1_common_proto_rawDescGZIP(), []int{1}
}

// Severity represents the severity level of an alert.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_LOW         Severity = 1
	Severity_SEVERITY_MEDIUM      Severity = 2
	Severity_SEVERITY_HIGH        Severity = 3
	Severity_SEVERITY_CRITICAL    Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_LOW",
		2: "SEVERITY_MEDIUM",
		3: "SEVERITY_HIGH",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_LOW":         1,
		"SEVERITY_MEDIUM":      2,
		"SEVERITY_HIGH":        3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_blazelog_v1_common_proto_enumTypes[2].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_blazelog_v1_common_proto_enumTypes[2]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_blazelog_v1_common_proto_rawDescGZIP(), []int{2}
}

var File_blazelog_v1_common_proto protoreflect.FileDescriptor

const file_blazelog_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x18blazelog/v1/common.proto\x12\vblazelog.v1*\x8f\x01\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x15\n" +
	"\x11LOG_LEVEL_WARNING\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04\x12\x13\n" +
	"\x0fLOG_LEVEL_FATAL\x10\x05*\x93\x01\n" +
	"\aLogType\x12\x18\n" +
	"\x14LOG_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eLOG_TYPE_NGINX\x10\x01\x12\x13\n" +
	"\x0fLOG_TYPE_APACHE\x10\x02\x12\x14\n" +
	"\x10LOG_TYPE_MAGENTO\x10\x03\x12\x17\n" +
	"\x13LOG_TYPE_PRESTASHOP\x10\x04\x12\x16\n" +
	"\x12LOG_TYPE_WORDPRESS\x10\x05*u\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x04B\xb6\x01\n" +
	"\x0fcom.blazelog.v1B\vCommonProtoP\x01ZIgithub.com/good-yellow-bee/blazelog/internal/proto/blazelog/v1;blazelogv1\xa2\x02\x03BXX\xaa\x02\vBlazelog.V1\xca\x02\vBlazelog\\V1\xe2\x02\x17Blazelog\\V1\\GPBMetadata\xea\x02\fBlazelog::V1b\x06proto3"

var (
	file_blazelog_v1_common_proto_rawDescOnce sync.Once
	file_blazelog_v1_common_proto_rawDescData []byte
)

func file_blazelog_v1_common_proto_rawDescGZIP() []byte {
	file_blazelog_v1_common_proto_rawDescOnce.Do(func() {
		file_blazelog_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blazelog_v1_common_proto_rawDesc), len(file_blazelog_v1_common_proto_rawDesc)))
	})
	return file_blazelog_v1_common_proto_rawDescData
}

var file_blazelog_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_blazelog_v1_common_proto_goTypes = []any{
	(LogLevel)(0), // 0: blazelog.v1.LogLevel
	(LogType)(0),  // 1: blazelog.v1.LogType
	(Severity)(0), // 2: blazelog.v1.Severity
}
var file_blazelog_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blazelog_v1_common_proto_init() }
func file_blazelog_v1_common_proto_init() {
	if File_blazelog_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blazelog_v1_common_proto_rawDesc), len(file_blazelog_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blazelog_v1_common_proto_goTypes,
		DependencyIndexes: file_blazelog_v1_common_proto_depIdxs,
		EnumInfos:         file_blazelog_v1_common_proto_enumTypes,
	}.Build()
	File_blazelog_v1_common_proto = out.File
	file_blazelog_v1_common_proto_goTypes = nil
	file_blazelog_v1_common_proto_depIdxs = nil
}
