// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blazelog/v1/log.proto

package blazelogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEntry represents a single parsed log entry.
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When the log event occurred.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Severity level of the log.
	Level LogLevel `protobuf:"varint,2,opt,name=level,proto3,enum=blazelog.v1.LogLevel" json:"level,omitempty"`
	// Main log message content.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Source identifies where the log came from (optional).
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// Log format type (nginx, apache, etc.).
	Type LogType `protobuf:"varint,5,opt,name=type,proto3,enum=blazelog.v1.LogType" json:"type,omitempty"`
	// Original unparsed log line (optional).
	Raw string `protobuf:"bytes,6,opt,name=raw,proto3" json:"raw,omitempty"`
	// Additional parsed fields (status code, request path, etc.).
	Fields *structpb.Struct `protobuf:"bytes,7,opt,name=fields,proto3" json:"fields,omitempty"`
	// Key-value pairs for categorization.
	Labels map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Line number in the source file.
	LineNumber int64 `protobuf:"varint,9,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	// Path to the source file.
	FilePath      string `protobuf:"bytes,10,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_blazelog_v1_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetType() LogType {
	if x != nil {
		return x.Type
	}
	return LogType_LOG_TYPE_UNSPECIFIED
}

func (x *LogEntry) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *LogEntry) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LogEntry) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *LogEntry) GetLineNumber() int64 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *LogEntry) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// LogBatch contains multiple log entries for efficient streaming.
type LogBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batch of log entries.
	Entries []*LogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Agent that sent this batch.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Sequence number for ordering/deduplication.
	Sequence uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Project this batch belongs to (all entries inherit this).
	ProjectId     string `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_blazelog_v1_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_log_proto_rawDescGZIP(), []int{1}
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LogBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogBatch) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LogBatch) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

var File_blazelog_v1_log_proto protoreflect.FileDescriptor

const file_blazelog_v1_log_proto_rawDesc = "" +
	"\n" +
	"\x15blazelog/v1/log.proto\x12\vblazelog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18blazelog/v1/common.proto\"\xc4\x03\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x05level\x18\x02 \x01(\x0e2\x15.blazelog.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12(\n" +
	"\x04type\x18\x05 \x01(\x0e2\x14.blazelog.v1.LogTypeR\x04type\x12\x10\n" +
	"\x03raw\x18\x06 \x01(\tR\x03raw\x12/\n" +
	"\x06fields\x18\a \x01(\v2\x17.google.protobuf.StructR\x06fields\x129\n" +
	"\x06labels\x18\b \x03(\v2!.blazelog.v1.LogEntry.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vline_number\x18\t \x01(\x03R\n" +
	"lineNumber\x12\x1b\n" +
	"\tfile_path\x18\n" +
	" \x01(\tR\bfilePath\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\bLogBatch\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.blazelog.v1.LogEntryR\aentries\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectIdB\xb3\x01\n" +
	"\x0fcom.blazelog.v1B\bLogProtoP\x01ZIgithub.com/good-yellow-bee/blazelog/internal/proto/blazelog/v1;blazelogv1\xa2\x02\x03BXX\xaa\x02\vBlazelog.V1\xca\x02\vBlazelog\\V1\xe2\x02\x17Blazelog\\V1\\GPBMetadata\xea\x02\fBlazelog::V1b\x06proto3"

var (
	file_blazelog_v1_log_proto_rawDescOnce sync.Once
	file_blazelog_v1_log_proto_rawDescData []byte
)

func file_blazelog_v1_log_proto_rawDescGZIP() []byte {
	file_blazelog_v1_log_proto_rawDescOnce.Do(func() {
		file_blazelog_v1_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blazelog_v1_log_proto_rawDesc), len(file_blazelog_v1_log_proto_rawDesc)))
	})
	return file_blazelog_v1_log_proto_rawDescData
}

var file_blazelog_v1_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blazelog_v1_log_proto_goTypes = []any{
	(*LogEntry)(nil),              // 0: blazelog.v1.LogEntry
	(*LogBatch)(nil),              // 1: blazelog.v1.LogBatch
	nil,                           // 2: blazelog.v1.LogEntry.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(LogLevel)(0),                 // 4: blazelog.v1.LogLevel
	(LogType)(0),                  // 5: blazelog.v1.LogType
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
}
var file_blazelog_v1_log_proto_depIdxs = []int32{
	3, // 0: blazelog.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: blazelog.v1.LogEntry.level:type_name -> blazelog.v1.LogLevel
	5, // 2: blazelog.v1.LogEntry.type:type_name -> blazelog.v1.LogType
	6, // 3: blazelog.v1.LogEntry.fields:type_name -> google.protobuf.Struct
	2, // 4: blazelog.v1.LogEntry.labels:type_name -> blazelog.v1.LogEntry.LabelsEntry
	0, // 5: blazelog.v1.LogBatch.entries:type_name -> blazelog.v1.LogEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_blazelog_v1_log_proto_init() }
func file_blazelog_v1_log_proto_init() {
	if File_blazelog_v1_log_proto != nil {
		return
	}
	file_blazelog_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blazelog_v1_log_proto_rawDesc), len(file_blazelog_v1_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blazelog_v1_log_proto_goTypes,
		DependencyIndexes: file_blazelog_v1_log_proto_depIdxs,
		MessageInfos:      file_blazelog_v1_log_proto_msgTypes,
	}.Build()
	File_blazelog_v1_log_proto = out.File
	file_blazelog_v1_log_proto_goTypes = nil
	file_blazelog_v1_log_proto_depIdxs = nil
}
