// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blazelog/v1/service.proto

package blazelogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamResponse is sent from server to agent during log streaming.
type StreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence number being acknowledged.
	AckedSequence uint64 `protobuf:"varint,1,opt,name=acked_sequence,json=ackedSequence,proto3" json:"acked_sequence,omitempty"`
	// Optional command from server.
	Command *ServerCommand `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// Optional error message.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_blazelog_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blazelog_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_blazelog_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *StreamResponse) GetAckedSequence() uint64 {
	if x != nil {
		return x.AckedSequence
	}
	return 0
}

func (x *StreamResponse) GetCommand() *ServerCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_blazelog_v1_service_proto protoreflect.FileDescriptor

const file_blazelog_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19blazelog/v1/service.proto\x12\vblazelog.v1\x1a\x17blazelog/v1/agent.proto\x1a\x15blazelog/v1/log.proto\"\x83\x01\n" +
	"\x0eStreamResponse\x12%\n" +
	"\x0eacked_sequence\x18\x01 \x01(\x04R\rackedSequence\x124\n" +
	"\acommand\x18\x02 \x01(\v2\x1a.blazelog.v1.ServerCommandR\acommand\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xe7\x01\n" +
	"\n" +
	"LogService\x12G\n" +
	"\bRegister\x12\x1c.blazelog.v1.RegisterRequest\x1a\x1d.blazelog.v1.RegisterResponse\x12D\n" +
	"\n" +
	"StreamLogs\x12\x15.blazelog.v1.LogBatch\x1a\x1b.blazelog.v1.StreamResponse(\x010\x01\x12J\n" +
	"\tHeartbeat\x12\x1d.blazelog.v1.HeartbeatRequest\x1a\x1e.blazelog.v1.HeartbeatResponseB\xb7\x01\n" +
	"\x0fcom.blazelog.v1B\fServiceProtoP\x01ZIgithub.com/good-yellow-bee/blazelog/internal/proto/blazelog/v1;blazelogv1\xa2\x02\x03BXX\xaa\x02\vBlazelog.V1\xca\x02\vBlazelog\\V1\xe2\x02\x17Blazelog\\V1\\GPBMetadata\xea\x02\fBlazelog::V1b\x06proto3"

var (
	file_blazelog_v1_service_proto_rawDescOnce sync.Once
	file_blazelog_v1_service_proto_rawDescData []byte
)

func file_blazelog_v1_service_proto_rawDescGZIP() []byte {
	file_blazelog_v1_service_proto_rawDescOnce.Do(func() {
		file_blazelog_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blazelog_v1_service_proto_rawDesc), len(file_blazelog_v1_service_proto_rawDesc)))
	})
	return file_blazelog_v1_service_proto_rawDescData
}

var file_blazelog_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blazelog_v1_service_proto_goTypes = []any{
	(*StreamResponse)(nil),    // 0: blazelog.v1.StreamResponse
	(*ServerCommand)(nil),     // 1: blazelog.v1.ServerCommand
	(*RegisterRequest)(nil),   // 2: blazelog.v1.RegisterRequest
	(*LogBatch)(nil),          // 3: blazelog.v1.LogBatch
	(*HeartbeatRequest)(nil),  // 4: blazelog.v1.HeartbeatRequest
	(*RegisterResponse)(nil),  // 5: blazelog.v1.RegisterResponse
	(*HeartbeatResponse)(nil), // 6: blazelog.v1.HeartbeatResponse
}
var file_blazelog_v1_service_proto_depIdxs = []int32{
	1, // 0: blazelog.v1.StreamResponse.command:type_name -> blazelog.v1.ServerCommand
	2, // 1: blazelog.v1.LogService.Register:input_type -> blazelog.v1.RegisterRequest
	3, // 2: blazelog.v1.LogService.StreamLogs:input_type -> blazelog.v1.LogBatch
	4, // 3: blazelog.v1.LogService.Heartbeat:input_type -> blazelog.v1.HeartbeatRequest
	5, // 4: blazelog.v1.LogService.Register:output_type -> blazelog.v1.RegisterResponse
	0, // 5: blazelog.v1.LogService.StreamLogs:output_type -> blazelog.v1.StreamResponse
	6, // 6: blazelog.v1.LogService.Heartbeat:output_type -> blazelog.v1.HeartbeatResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blazelog_v1_service_proto_init() }
func file_blazelog_v1_service_proto_init() {
	if File_blazelog_v1_service_proto != nil {
		return
	}
	file_blazelog_v1_agent_proto_init()
	file_blazelog_v1_log_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blazelog_v1_service_proto_rawDesc), len(file_blazelog_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blazelog_v1_service_proto_goTypes,
		DependencyIndexes: file_blazelog_v1_service_proto_depIdxs,
		MessageInfos:      file_blazelog_v1_service_proto_msgTypes,
	}.Build()
	File_blazelog_v1_service_proto = out.File
	file_blazelog_v1_service_proto_goTypes = nil
	file_blazelog_v1_service_proto_depIdxs = nil
}
